### ISSUE TITLE
502 Bad gateway and no folder www/matomo

### ISSUE THREAD

**Issue by perarg** [tiredofit/docker-matomo#1]
Hello,
i am using https://github.com/tiredofit/docker-nginx-php-fpm for some project with success. I try this one but it fails. I use a simple docker-compose.yml file
```
version: '3'

services:
  matomo-app:
    image: tiredofit/matomo
    container_name: matomo-app
    userns_mode: 'host'
    volumes:
      #- ./data:/www/matomo
      #- ./logs:/www/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=stats.mydomain.com
      - VIRTUAL_NETWORK=webproxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=stats.mydomain.com
      - LETSENCRYPT_EMAIL=mail@mymail.com

      #- ZABBIX_HOSTNAME=matomo-app

      - DB_HOST=mariadb
      - DB_NAME=dbForMatomo
      - DB_USER=usernameForMatomo
      - DB_PASS=passwordForMatomo 
  
      - CRON_PERIOD=60
    networks:
      - default
    restart: always

networks:
  default:
    external:
      name: webproxy
```

No redis. I use my already mariadb instance. What i get:
* A 502 Bad Gateway. I cannot explain why. All other containers (docker-nginx-php-fpm) at 80/TCP are working great.
* When i `docker exec -it matomo-app bash` the www folder has only a folder __log__. There is not __matomo__ folder. Is it normal ?

**UPDATE:**
I think there is no installation command for __matomo__ in Dockerfile.
I also noticed that there is a wrong line `echo 'geoip.custom_directory=/www/piwik/misc' >> /etc/php7/php.ini && \`. It's /www/matomo/misc, right ?
